# Generated by Django 5.0.6 on 2024-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lost_date", models.DateField(verbose_name="Lost Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("휴대폰", "휴대폰"),
                            ("지갑", "지갑"),
                            ("가방", "가방"),
                            ("노트북", "노트북"),
                            ("이어폰", "이어폰"),
                            ("옷", "옷"),
                            ("신분증", "신분증"),
                            ("악세사리", "악세사리"),
                            ("화장품", "화장품"),
                            ("우산", "우산"),
                            ("카드", "카드"),
                            ("전자기기", "전자기기"),
                            ("책", "책"),
                            ("악기", "악기"),
                            ("전자담배", "전자담배"),
                            ("기타", "기타"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("회색", "회색"),
                            ("빨간색", "빨간색"),
                            ("주황색", "주황색"),
                            ("핑크색", "핑크색"),
                            ("파란색", "파란색"),
                            ("보라색", "보라색"),
                            ("노란색", "노란색"),
                            ("초록색", "초록색"),
                            ("갈색", "갈색"),
                            ("흰색", "흰색"),
                            ("검은색", "검은색"),
                        ],
                        max_length=50,
                        verbose_name="Color",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Found Location"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lost_items/",
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
    ]
